services:
  webapi:
    build: ./WebApi
    ports:
      - "5001:5001"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gbs
      - MONGO_INITDB_ROOT_PASSWORD=geheim

volumes:
  mongodbdata:
